### ISSUE TITLE
DLL crashes on Frontend state (Polaris-CH2)

### ISSUE THREAD

**Issue by Cubed** [PolarisV2/Polaris#2]
Compiled with adding Actors to 14.30 SDK. When DLL is injected it freezes then crashes on Frontend state.

**Comment by Beat-YT** [comment]
@Cubed Can u send the Polaris-CH2 your using?

**Comment by Cubed** [comment]
Nvm was confirmed by Cyuubi that DLL never worked.

**Comment by Beat-YT** [comment]
Then close the issue

**Comment by Beat-YT** [comment]
@Cubed close the issue

**Comment by pivotman319-new** [comment]
Project's dead and we're not offering support for it.
